import fs from 'node:fs';
const p=process.argv[2]; if(!p) throw new Error('usage: patch-server.mjs <server.js>');
let s=fs.readFileSync(p,'utf8');
const stateAnchor="const SYNC_STATE_FILE = path.join(DATA_DIR, 'phone-sync-state.json');";
if(!s.includes(stateAnchor)) throw new Error('sync state anchor missing');
s=s.replace(stateAnchor, () => stateAnchor+"\nconst SYNC_CONTROL_FILE = path.join(DATA_DIR, 'phone-sync-control.json');");
const saveAnchor=`function savePhoneSyncState() {\n  ensureDataDir();\n  fs.writeFileSync(SYNC_STATE_FILE, JSON.stringify(PHONE_SYNC, null, 2));\n}`;
if(!s.includes(saveAnchor)) throw new Error('savePhoneSyncState anchor missing');
const controlFns=`${saveAnchor}\nfunction loadPhoneSyncControl() {\n  try {\n    if (fs.existsSync(SYNC_CONTROL_FILE)) {\n      const value = JSON.parse(fs.readFileSync(SYNC_CONTROL_FILE, 'utf8'));\n      return { enabled: value?.enabled === true };\n    }\n  } catch (_) {}\n  return { enabled: false };\n}\nlet PHONE_SYNC_CONTROL = loadPhoneSyncControl();\nfunction savePhoneSyncControl() {\n  ensureDataDir();\n  fs.writeFileSync(SYNC_CONTROL_FILE, JSON.stringify(PHONE_SYNC_CONTROL, null, 2));\n}\nfunction phoneSyncEnabled() { return PHONE_SYNC_CONTROL.enabled === true; }\nfunction stopPhoneSync() {\n  if (phoneSyncTimer) clearInterval(phoneSyncTimer);\n  phoneSyncTimer = null;\n  PHONE_SYNC.connected = false;\n  savePhoneSyncState();\n}`;
s=s.replace(saveAnchor, () => controlFns);
const pollAnchor=`async function pollPhoneSync() {\n  if (phoneSyncBusy) return { ok: true, busy: true, ...PHONE_SYNC };`;
if(!s.includes(pollAnchor)) throw new Error('poll anchor missing');
s=s.replace(pollAnchor, () => `async function pollPhoneSync() {\n  if (!phoneSyncEnabled()) return { ok: true, ...PHONE_SYNC, enabled: false, configured: !!loadPhoneSyncConfig(), busy: false, connected: false };\n  if (phoneSyncBusy) return { ok: true, ...PHONE_SYNC, enabled: true, busy: true };`);
const startAnchor=`function startPhoneSync() {\n  if (phoneSyncTimer) return;\n  ensureDir(SYNC_INBOX_DIR);\n  phoneSyncTimer = setInterval(() => { pollPhoneSync().catch(() => {}); }, SYNC_POLL_MS);\n  setTimeout(() => { pollPhoneSync().catch(() => {}); }, 1200).unref();\n}`;
if(!s.includes(startAnchor)) throw new Error('startPhoneSync anchor missing');
s=s.replace(startAnchor, () => `function startPhoneSync() {\n  ensureDir(SYNC_INBOX_DIR);\n  if (!phoneSyncEnabled()) { stopPhoneSync(); return; }\n  if (phoneSyncTimer) return;\n  phoneSyncTimer = setInterval(() => { pollPhoneSync().catch(() => {}); }, SYNC_POLL_MS);\n  setTimeout(() => { pollPhoneSync().catch(() => {}); }, 1200).unref();\n}`);
const routeAnchor=`app.get('/sync/status', (req, res) => res.json({ ok: true, configured: !!loadPhoneSyncConfig(), busy: phoneSyncBusy, ...PHONE_SYNC }));`;
if(!s.includes(routeAnchor)) throw new Error('sync status route anchor missing');
const routes=`app.get('/api/synthia/status', (_req, res) => res.json({ ok: true, backend: 'online', pure_synthia: pureSynthiaStatus(), remote_sync: { enabled: phoneSyncEnabled(), configured: !!loadPhoneSyncConfig(), busy: phoneSyncBusy, connected: phoneSyncEnabled() && PHONE_SYNC.connected, last_success_at: PHONE_SYNC.last_success_at, last_error: PHONE_SYNC.last_error } }));\n${routeAnchor.replace('busy: phoneSyncBusy, ...PHONE_SYNC','...PHONE_SYNC, enabled: phoneSyncEnabled(), busy: phoneSyncBusy, connected: phoneSyncEnabled() && PHONE_SYNC.connected')}\napp.post('/sync/control', (req, res) => {\n  const enabled = req.body?.enabled === true;\n  PHONE_SYNC_CONTROL = { enabled };\n  savePhoneSyncControl();\n  if (enabled) startPhoneSync(); else stopPhoneSync();\n  res.json({ ok: true, ...PHONE_SYNC, enabled, configured: !!loadPhoneSyncConfig(), connected: enabled && PHONE_SYNC.connected });\n});`;
s=s.replace(routeAnchor, () => routes);
fs.writeFileSync(p,s);
